// `.env.ts` is generated by the `npm run env` command
import env from '@env/.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://hbkuoverview.herokuapp.com/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [ 'en-US' ]
};
